export const V0_TIMESTAMP = 1712696400;
export const VALIDATORS_CACHE_KEY = '__0L_VALIDATORS__';
export const TOP_BALANCE_ACCOUNTS_CACHE_KEY = '__0L_TOP_BALANCE_ACCOUNTS__';
export const COMMUNITY_WALLETS_CACHE_KEY = '__0L_COMMUNITY_WALLETS__';
export const COMMUNITY_WALLETS_STATS_CACHE_KEY = '__0L_COMMUNITY_WALLETS_STATS__';
export const COMMUNITY_WALLETS_DETAILS_CACHE_KEY = '__0L_COMMUNITY_WALLETS_DETAILS__';
export const COMMUNITY_WALLETS_PAYMENTS_CACHE_KEY = '__0L_COMMUNITY_WALLETS_PAYMENTS__';
