export const V0_TIMESTAMP = 1712696400;
export const TOP_BALANCE_ACCOUNTS_CACHE_KEY = "__0L_TOP_BALANCE_ACCOUNTS__";
export const COMMUNITY_WALLETS_CACHE_KEY = "__0L_COMMUNITY_WALLETS__";
export const VALIDATORS_CACHE_KEY = "__0L_VALIDATORS__";
