export const STATS_CACHE_KEY = '__0L_CACHED_STATS__';
export const ACCOUNTS_STATS_CACHE_KEY = '__0L_CACHED_ACCOUNTS_STATS__';
export const TOP_LIQUID_ACCOUNTS_CACHE_KEY = '__0L_CACHED_TOP_LIQUID_ACCOUNTS__';
