INSERT INTO "user_transaction_v7" (
  "version",
  "hash",
  "gas_used",
  "success",
  "vm_status",
  "sender",
  "sequence_number",
  "max_gas_amount",
  "gas_unit_price",
  "expiration_timestamp",
  "module_address",
  "module_name",
  "function_name",
  "type_arguments",
  "arguments",
  "type",
  "timestamp"
)
SELECT
  "version",
  reinterpretAsUInt256(reverse(unhex("hash"))),
  "gas_used",
  "success",
  "vm_status",
  reinterpretAsUInt256(reverse(unhex("sender"))),
  "sequence_number",
  "max_gas_amount",
  "gas_unit_price",
  "expiration_timestamp",
  reinterpretAsUInt256(reverse(unhex("module_address"))),
  "module_name",
  "function_name",
  "type_arguments",
  "arguments",
  "type",
  "timestamp"
FROM
  input('
      version UInt64,
      hash String,
      gas_used UInt64,
      success Boolean,
      vm_status String,
      sender String,
      sequence_number UInt64,
      max_gas_amount UInt64,
      gas_unit_price UInt64,
      expiration_timestamp UInt64,
      module_address String,
      module_name String,
      function_name String,
      type_arguments String,
      arguments String,
      type String,
      timestamp UInt64
  ')
  FORMAT Parquet