name: Build Web App

on:
  push:
    paths:
      - web-app/**
      - .github/workflows/build-web-app.yml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/0lnetworkcommunity/explorer/web-app
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CI_COMMIT_SHA=${{ github.sha }}

      - name: Render k8s manifests
        run: |
          export GITHUB_SHA="${{ github.sha }}"

          envsubst < .templates/infra/web-app/deployment.yaml > infra/web-app/deployment.yaml

          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git add infra/web-app/deployment.yaml

          git commit -m "Update web-app deployment" || echo "No changes to commit"
          git push