name: Build Web App Container Image

on:
  push:
    paths:
      - web-app/**
      - .github/workflows/build-web-app-container.yml
    branches:
      - main
      - build-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/web-app
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long

      - name: Log in to Container Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CI_COMMIT_SHA=${{ github.sha }}
