name: Update Changelog

on:
  push:
    branches:
      - feat/lei_changelog_dev

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Install Node.js and NPM packages
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Generate changelog and bump version
      run: |
        cd web-app/
        npx standard-version
        git push --follow-tags origin master
